version: '2.4'
services:

  postgres_backup:
    build: .
    mem_limit: 50mb
    cpus: 0.5
    tty: true
    command: /bin/sh
    environment:
      REMOTE_URL: ''
      PARAMS: ''
      POSTGRES_DUMP_PARAMS: ''
      POSTGRES_RESTORE_PARAMS: ''
      BACKUP_LIFETIME: ''
      BACKUP_TIME: ''
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      TELEGRAM_TOKEN: ''
      TELEGRAM_CHAT_ID: ''
    volumes:
      - ./cache:/root/.cache/duplicity
    links:
      - db:postgres

  db:
    image: postgres:11.1
